name: montbest2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.10
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0  # Add this line
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  assets:
    - lib/assets/image/badge_novice.jpeg
    - lib/assets/image/badge_regular.jpeg
    - lib/assets/image/badge_expert.jpeg

    - lib/assets/logo2.png



